name: ConditionalEffects
main: fun.sunrisemc.effects.ConditionalEffectsPlugin
version: 1.0.2
api-version: 1.18
author: TheFishNextDoor
description: This is a simple Bukkit Plugin
commands:
  conditionaleffects:
    description: Shows a hello message to the player
    usage: /conditionaleffects [subcommand]
    permission: conditionaleffects
    aliases: [ceffects, ce]
permissions:
  conditionaleffects.reload:
    description: Allows the user to reload the plugin
  conditonaleffects.give:
    description: Allows the user to give conditional effects to players
  conditionaleffects.check:
    description: Allows the user to manually check conditional effects on players